#!/bin/bash

# SIG handler
# Needs handler
# exit_gracefully(){

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

source venv/bin/activate

cd backend
pip install -r requirements.txt

cd app
flask run &
sleep 5

cd ../../frontend
if [ ! -d "frontend" ]; then
    npm create vite@latest frontend -- --template react
    npm install axios
fi
npm run dev

#trap 'exit_gracefully' SIGINT

#while true; do
#	sleep 1
#done



