#!/bin/bash

# SIG handler
exit_gracefully(){
	pkill -P $$
	deactivate

	echo 
	echo "***************************"
	echo "*                         *"
	echo "*        Goodbye...       *"
	echo "*                         *"
	echo "***************************"
	echo 
	
	exit 0
}

trap 'exit_gracefully' SIGINT

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

source venv/bin/activate

cd backend
pip install -r requirements.txt

cd src
flask run &
sleep 2

cd ../../frontend
npm install

npm run dev &

while true;
do
	sleep 1
done



